#日志设置
logging:
  config: classpath:logback.xml
  
#服务器设置
server:
  port: 1111
  
#数据源设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/server?characterEncoding=utf8
    username: test
    password: 123456

#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
    
        